---
abstract: 'International Atomic Time and realisations'
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
build_requires:
  Math::BigRat: 0.04
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  Module::Build: 0
  perl: 5.006
  strict: 0
  warnings: 0
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-TAI
provides:
  Time::TAI:
    file: lib/Time/TAI.pm
    version: 0.003
  Time::TAI::Realisation_TAI:
    file: lib/Time/TAI/Realisation_TAI.pm
    version: 0.003
requires:
  Carp: 0
  Exporter: 0
  LWP: 5.5394
  LWP::UserAgent: 0
  Math::BigRat: 0.04
  Math::Interpolator::Robust: 0
  Math::Interpolator::Source: 0
  Time::TT::InterpolatingRealisation: 0
  Time::TT::OffsetKnot: 0.004
  Time::TT::Realisation: 0
  constant: 0
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.003
